/* Golden + error tests for the ctmpl generator.
 *
 * The generator API is exercised in-process (open_memstream), so the
 * tests check the exact generated text without touching the file
 * system. Exact goldens cover the core shapes; the longer feature
 * tests use substring checks to stay robust against cosmetic output
 * changes.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "ctmpl.h"
#include "test.h"

/* Compiles src; returns 0 on success (h/c receive the output) or -1
 * (err receives the error). Always NUL-terminates the outputs. */
static int run(const char *src, char **h, char **c, CtmplError *err)
{
    *h = NULL; /* never leave dangling pointers behind on failure */
    *c = NULL;
    FILE *fh = NULL;
    FILE *fc = NULL;
    char *bh = NULL;
    char *bc = NULL;
    size_t zh = 0;
    size_t zc = 0;

    fh = open_memstream(&bh, &zh);
    fc = open_memstream(&bc, &zc);
    if (fh == NULL || fc == NULL) {
        fclose(fh);
        fclose(fc);
        free(bh);
        free(bc);
        return -1;
    }
    int rc = ctmpl_compile(src, strlen(src), "test.thtml", fh, fc, err);
    fclose(fh);
    fclose(fc);
    if (rc != 0) {
        free(bh);
        free(bc);
        return -1;
    }
    *h = bh;
    *c = bc;
    return 0;
}

static void free_run(char *h, char *c)
{
    free(h);
    free(c);
}

/* CHECK that `needle` occurs in the generated code. */
#define IN_C(needle)     CHECK(strstr(c, (needle)) != NULL)
#define IN_H(needle)     CHECK(strstr(h, (needle)) != NULL)
#define NOT_IN_C(needle) CHECK(strstr(c, (needle)) == NULL)

static void expect_error(const char *src, const char *needle, size_t line);

/* ------------------------------------------------------------------ */
/* exact goldens                                                      */
/* ------------------------------------------------------------------ */

static void test_golden_simple(void)
{
    static const char *src =
        "component greeting(const char *name) {\n"
        "  <div class=\"greeting\">Hello, { name }!</div>\n"
        "}\n";
    static const char *want_h =
        "/* Generated by ctmpl from test.thtml - DO NOT EDIT */\n"
        "#ifndef TEST_TEMPL_H\n"
        "#define TEST_TEMPL_H\n"
        "\n"
        "#include \"c_http_tpl.h\"\n"
        "\n"
        "void tpl_greeting(TplOut *out, const char *name);\n"
        "\n"
        "#endif /* TEST_TEMPL_H */\n";
    static const char *want_c =
        "/* Generated by ctmpl from test.thtml - DO NOT EDIT */\n"
        "#include \"test_templ.h\"\n"
        "\n"
        "void tpl_greeting(TplOut *out, const char *name)\n"
        "{\n"
        "#line 1 \"test.thtml\"\n"
        "    tpl_lit(out, \"\\n  <div class=\\\"greeting\\\">Hello, \");\n"
        "#line 2 \"test.thtml\"\n"
        "    tpl_esc(out, (name));\n"
        "    tpl_lit(out, \"!</div>\");\n"
        "}\n\n";

    char *h = NULL;
    char *c = NULL;
    CtmplError err;
    CHECK(run(src, &h, &c, &err) == 0);
    CHECK(h != NULL && strcmp(h, want_h) == 0);
    CHECK(c != NULL && strcmp(c, want_c) == 0);
    free_run(h, c);
}

static void test_golden_control_flow(void)
{
    static const char *src = "component t(const Page *p) {\n"
                             "  if p->count > 0 {\n"
                             "    <p>many</p>\n"
                             "  } else if p->count == 0 {\n"
                             "    <p>none</p>\n"
                             "  } else {\n"
                             "    <p>odd</p>\n"
                             "  }\n"
                             "}\n";
    char *h = NULL;
    char *c = NULL;
    CtmplError err;
    CHECK(run(src, &h, &c, &err) == 0);
    IN_C("if (p->count > 0) {");
    IN_C("} else if (p->count == 0) {");
    IN_C("} else {");
    IN_C("<p>many</p>");
    IN_C("<p>none</p>");
    IN_C("<p>odd</p>");
    IN_H("void tpl_t(TplOut *out, const Page *p);");
    free_run(h, c);
}

static void test_golden_attributes(void)
{
    static const char *src =
        "component a(const Item *it) {\n"
        "  <li class=\"item\" href={ tpl_url(out, it->url) } "
        "hidden?={ it->gone }>{ it->label }</li>\n"
        "}\n";
    char *h = NULL;
    char *c = NULL;
    CtmplError err;
    CHECK(run(src, &h, &c, &err) == 0);
    IN_C("tpl_lit(out, \"\\n  <li class=\\\"item\\\" href=\\\"\");");
    IN_C("tpl_attr_url(out, (tpl_url(out, it->url)));");
    IN_C("tpl_lit(out, \"\\\" \");");
    IN_C("if (it->gone) {");
    IN_C("tpl_lit(out, \" hidden\");");
    IN_C("tpl_esc(out, (it->label));");
    free_run(h, c);
}

/* ------------------------------------------------------------------ */
/* feature checks                                                     */
/* ------------------------------------------------------------------ */

static void test_features(void)
{
    static const char *src = "#include \"page.h\"\n"
                             "\n"
                             "component loop(size_t n) {\n"
                             "  <ul>\n"
                             "  for size_t i = 0; i < n; i++ {\n"
                             "    <li>{ tpl_int(out, i) }</li>\n"
                             "  }\n"
                             "  </ul>\n"
                             "}\n"
                             "\n"
                             "component raw_demo(const char *html) {\n"
                             "  @raw(html)\n"
                             "}\n"
                             "\n"
                             "component quote_demo(const char *v) {\n"
                             "  <p title=\"static and { v } mixed\">x</p>\n"
                             "}\n";
    char *h = NULL;
    char *c = NULL;
    CtmplError err;
    CHECK(run(src, &h, &c, &err) == 0);

    /* #-line lands in the .h, verbatim */
    IN_H("#include \"page.h\"");
    NOT_IN_C("#include \"page.h\"");

    /* for loop */
    IN_C("for (size_t i = 0; i < n; i++) {");
    IN_C("tpl_esc(out, (tpl_int(out, i)));");

    /* @raw */
    IN_C("tpl_raw(out, (html));");

    /* interpolation inside a quoted attribute value */
    IN_C("title=\\\"static and \");");
    IN_C("tpl_attr(out, (v));");
    free_run(h, c);
}

static void test_children(void)
{
    static const char *src = "component wrap(TplChildren *children) {\n"
                             "  <div>{ children... }</div>\n"
                             "}\n"
                             "\n"
                             "component show(const char *msg) {\n"
                             "  @wrap() {\n"
                             "    <p>{ msg }</p>\n"
                             "  }\n"
                             "}\n";
    char *h = NULL;
    char *c = NULL;
    CtmplError err;
    CHECK(run(src, &h, &c, &err) == 0);

    /* children render guard */
    IN_C("if (children != NULL && children->fn != NULL) {");
    IN_C("children->fn(out, children->data);");

    /* parameter capture: the lambda takes the ENCLOSING component's
     * parameter — the block references msg directly, no with() */
    IN_C("static void tpl__block_1(TplOut *out, const char *msg)");
    IN_C("tpl_esc(out, (msg));");

    /* the adapter matches TplChildren.fn and forwards the void * */
    IN_C("static void tpl__block_1_adapter(TplOut *out, void *tpl_data)");
    IN_C("tpl__block_1(out, tpl_data);");

    /* lambda + adapter are emitted before the component that uses them */
    const char *lambda = strstr(c, "static void tpl__block_1");
    const char *show = strstr(c, "void tpl_show(");
    CHECK(lambda != NULL);
    CHECK(show != NULL);
    CHECK(lambda < show);

    /* the call site binds the captured parameter through data */
    IN_C("TplChildren tpl_children = {tpl__block_1_adapter, "
         "(void *)(msg)};");
    IN_C("tpl_wrap(out, &tpl_children);");
    free_run(h, c);
}

static void test_children_with(void)
{
    /* explicit data binding: the block sees tpl_data (void *), the
     * call binds an arbitrary expression via with (...) */
    static const char *src =
        "component wrap(TplChildren *children, size_t a, size_t b) {\n"
        "  <div>{ children... }</div>\n"
        "}\n"
        "\n"
        "component show(const char *msgs[2]) {\n"
        "  @wrap(1, 2) with (msgs[0]) {\n"
        "    <p>{ (const char *)tpl_data }</p>\n"
        "  }\n"
        "}\n";
    char *h = NULL;
    char *c = NULL;
    CtmplError err;
    CHECK(run(src, &h, &c, &err) == 0);
    /* multi-param components cannot capture: untyped lambda */
    IN_C("static void tpl__block_1(TplOut *out, void *tpl_data)");
    IN_C("TplChildren tpl_children = {tpl__block_1, "
         "(void *)(msgs[0])};");
    IN_C("tpl_wrap(out, 1, 2, &tpl_children);");
    free_run(h, c);
}

static void test_fragment_once(void)
{
    static const char *src = "once note_style\n"
                             "\n"
                             "component feature_note(void) {\n"
                             "  @once(note_style) {\n"
                             "    <style>.note { color: #666; }</style>\n"
                             "  }\n"
                             "  <p class=\"note\">x</p>\n"
                             "}\n"
                             "\n"
                             "component home(const Page *p) {\n"
                             "  @fragment(\"links\") {\n"
                             "    <li>{ tpl_int(out, p->n) }</li>\n"
                             "  }\n"
                             "}\n";
    char *h = NULL;
    char *c = NULL;
    CtmplError err;
    CHECK(run(src, &h, &c, &err) == 0);

    /* once declaration: file-static handle with debug name */
    IN_C("static TplOnce note_style = {.name = \"note_style\"};");

    /* @once: wrapped in tpl_once_begin, block INLINE (no lambda) */
    IN_C("if (tpl_once_begin(out, &(note_style))) {");
    IN_C("<style>.note { color: #666; }</style>");
    NOT_IN_C("tpl__block_");

    /* @fragment: begin/end markers, body inline */
    IN_C("tpl_frag_begin(out, (\"links\"));");
    IN_C("tpl_frag_end(out);");
    IN_C("tpl_esc(out, (tpl_int(out, p->n)));");

    /* handle names do not leak into the .h */
    CHECK(strstr(h, "note_style") == NULL);
    free_run(h, c);
}

static void test_fragment_once_errors(void)
{
    /* @once without a block */
    expect_error("once h\n"
                 "component t(void) {\n"
                 "  @once(h)\n"
                 "}\n",
                 "@once requires a child block", 3);

    /* @fragment without an argument */
    expect_error("component t(void) {\n"
                 "  @fragment { <p>x</p> }\n"
                 "}\n",
                 "@fragment expects an argument", 2);

    /* with (...) on a builtin */
    expect_error("component t(void) {\n"
                 "  @fragment(\"x\") with (y) { <p>x</p> }\n"
                 "}\n",
                 "with (...) is not valid for @fragment", 2);

    /* component names may not shadow builtins */
    expect_error("component fragment(void) {\n"
                 "  <p>x</p>\n"
                 "}\n",
                 "collides with the runtime", 1);
    expect_error("component once(void) {\n"
                 "  <p>x</p>\n"
                 "}\n",
                 "collides with the runtime", 1);

    /* duplicate once declaration */
    expect_error("once h\n"
                 "once h\n"
                 "component t(void) {\n"
                 "  <p>x</p>\n"
                 "}\n",
                 "already declared", 2);
}

static void test_raw_text_elements(void)
{
    static const char *src =
        "component page(void) {\n"
        "  <script>if (x) { var y = 1 > 0; }</script>\n"
        "  <style>a { color: red; } b { color: blue; }</style>\n"
        "  <!-- comment with > inside -->\n"
        "}\n";
    char *h = NULL;
    char *c = NULL;
    CtmplError err;
    CHECK(run(src, &h, &c, &err) == 0);
    /* braces pass through uninterpreted in raw-text elements */
    IN_C("if (x) { var y = 1 > 0; }");
    IN_C("a { color: red; } b { color: blue; }");
    IN_C("<!-- comment with > inside -->");
    free_run(h, c);

    /* missing close tag for a raw-text element */
    CHECK(run("component page(void) {\n"
              "  <script>never closed\n"
              "}\n",
              &h, &c, &err) == -1);
    CHECK(strstr(err.message, "missing </script>") != NULL);
    free_run(h, c);
}

static void test_keyword_text_escaping(void)
{
    /* Text runs starting with if/for are statements — the docs say
     * to use expressions for literal text. */
    char *h = NULL;
    char *c = NULL;
    CtmplError err;
    CHECK(run("component t(void) {\n"
              "  { \"for a day\" }\n"
              "}\n",
              &h, &c, &err) == 0);
    IN_C("tpl_esc(out, (\"for a day\"));");
    free_run(h, c);

    /* a text run starting with "for" INSIDE an element body is
     * also an error — templ rejects the same thing (its docs use
     * <p>if a tree fell</p> as the canonical mistake) */
    CtmplError err2;
    CHECK(run("component t(void) {\n"
              "  <p>for a day</p>\n"
              "}\n",
              &h, &c, &err2) == -1);
    CHECK(strstr(err2.message, "unbalanced") != NULL);
    free_run(h, c);
}

static void test_no_params_and_empty_body(void)
{
    char *h = NULL;
    char *c = NULL;
    CtmplError err;
    CHECK(run("component empty(void) {\n"
              "}\n",
              &h, &c, &err) == 0);
    IN_H("void tpl_empty(TplOut *out);");
    IN_C("void tpl_empty(TplOut *out)");
    IN_C("(void)out;");
    free_run(h, c);
}

/* ------------------------------------------------------------------ */
/* HTML structure validation                                          */
/* ------------------------------------------------------------------ */

static void test_html_validation_valid(void)
{
    char *h = NULL;
    char *c = NULL;
    CtmplError err;

    /* nested tags, void elements, self-closed void elements */
    CHECK(run("component t(void) {\n"
              "  <div><p>x</p><img src=\"a.png\"><hr/><br></div>\n"
              "}\n",
              &h, &c, &err) == 0);
    IN_C("<div><p>x</p><img src=\\\"a.png\\\"><hr/><br></div>");
    free_run(h, c);

    /* tag names are case-insensitive: <DIV> closes with </div> */
    CHECK(run("component t(void) {\n"
              "  <DIV>x</div>\n"
              "}\n",
              &h, &c, &err) == 0);
    free_run(h, c);

    /* tags inside HTML comments do not affect the stack */
    CHECK(run("component t(void) {\n"
              "  <!-- <div><p> never closed </div> -->\n"
              "  <p>ok</p>\n"
              "}\n",
              &h, &c, &err) == 0);
    free_run(h, c);

    /* tags spanning statement blocks are fine in parse order */
    CHECK(run("component t(bool b) {\n"
              "  <ul>\n"
              "  if b {\n"
              "    <li>yes</li>\n"
              "  } else {\n"
              "    <li>no</li>\n"
              "  }\n"
              "  </ul>\n"
              "}\n",
              &h, &c, &err) == 0);
    free_run(h, c);

    /* script/style participate: <script> opens, </script> closes */
    CHECK(run("component t(void) {\n"
              "  <script>var x = 1;</script>\n"
              "}\n",
              &h, &c, &err) == 0);
    free_run(h, c);
}

static void test_html_validation_errors(void)
{
    /* mismatched close: points at the open tag's line */
    expect_error("component t(void) {\n"
                 "  <div><p>x</div>\n"
                 "}\n",
                 "</div> closes nothing — expected </p>", 2);

    /* unclosed at component end: points at the opening '<' */
    expect_error("component t(void) {\n"
                 "  <div><p>x</p>\n"
                 "}\n",
                 "unclosed <div>", 2);

    /* close without any open tag */
    expect_error("component t(void) {\n"
                 "  </p>\n"
                 "}\n",
                 "</p> closes nothing — no tag is open", 2);

    /* non-void self-closing: browsers ignore the slash */
    expect_error("component t(void) {\n"
                 "  <div/>\n"
                 "}\n",
                 "non-void elements need a real closing tag", 2);

    /* void elements cannot have a closing tag */
    expect_error("component t(void) {\n"
                 "  <input></input>\n"
                 "}\n",
                 "void elements cannot have a closing tag", 2);

    /* empty closing tag name */
    expect_error("component t(void) {\n"
                 "  <p>x</>\n"
                 "}\n",
                 "empty closing tag name", 2);

    /* tags must be balanced WITHIN one component (the stack resets
     * per component — a close in a later component is an error) */
    expect_error("component a(void) {\n"
                 "  <p>x</p>\n"
                 "}\n"
                 "\n"
                 "component b(void) {\n"
                 "  </p>\n"
                 "}\n",
                 "no tag is open", 6);
}

/* ------------------------------------------------------------------ */
/* attribute contexts (URL / style / on-rejection)                   */
/* ------------------------------------------------------------------ */

static void test_attr_contexts(void)
{
    static const char *src =
        "component a(const Item *it) {\n"
        "  <a href={ tpl_url(out, it->url) } src={ tpl_safe_url(it->u2) }\n"
        "    data-src={ it->x } class=\"c\">x</a>\n"
        "  <p style={ tpl_css(out, it->css) }>y</p>\n"
        "  <p title=\"static { it->t } mixed\">z</p>\n"
        "}\n";
    char *h = NULL;
    char *c = NULL;
    CtmplError err;
    CHECK(run(src, &h, &c, &err) == 0);

    /* URL attributes: TplUrl-forcing writer */
    IN_C("tpl_attr_url(out, (tpl_url(out, it->url)));");
    IN_C("tpl_attr_url(out, (tpl_safe_url(it->u2)));");

    /* data-* attributes are plain attribute context */
    IN_C("tpl_attr(out, (it->x));");

    /* style: the CSS sanitizer context */
    IN_C("tpl_attr_css(out, (tpl_css(out, it->css)));");

    /* quoted-attribute interps keep their attribute context */
    IN_C("tpl_attr(out, (it->t));");

    /* constant attribute values are untouched */
    IN_C("class=\\\"c\\\"");
    free_run(h, c);
}

static void test_attr_context_errors(void)
{
    /* on* attributes reject expressions (templ's injection rule) */
    expect_error("component t(const char *js) {\n"
                 "  <button onclick={ js }>x</button>\n"
                 "}\n",
                 "expressions in 'onclick' attributes are not supported", 2);

    /* hx-on:* is treated the same */
    expect_error("component t(const char *js) {\n"
                 "  <button hx-on:click={ js }>x</button>\n"
                 "}\n",
                 "expressions in 'hx-on:click' attributes", 2);

    /* constant on* attributes are fine */
    char *h = NULL;
    char *c = NULL;
    CtmplError err;
    CHECK(run("component t(void) {\n"
              "  <button onclick=\"alert(1)\">x</button>\n"
              "}\n",
              &h, &c, &err) == 0);
    IN_C("onclick=\\\"alert(1)\\\"");
    free_run(h, c);

    /* unwrapped URL attributes fail at C-COMPILE time with a clear
     * type error pointing into the .thtml — check the shape */
    CHECK(run("component t(const char *u) {\n"
              "  <a href={ u }>x</a>\n"
              "}\n",
              &h, &c, &err) == 0);
    IN_C("tpl_attr_url(out, (u));"); /* const char* vs TplUrl */
    free_run(h, c);
}

/* ------------------------------------------------------------------ */
/* error cases                                                        */
/* ------------------------------------------------------------------ */

static void expect_error(const char *src, const char *needle, size_t line)
{
    char *h = NULL;
    char *c = NULL;
    CtmplError err;
    CHECK(run(src, &h, &c, &err) == -1);
    CHECK_MSG(strstr(err.message, needle) != NULL, err.message);
    CHECK_MSG(err.line == line, err.message);
    free_run(h, c);
}

static void test_errors(void)
{
    /* stray brace in text */
    expect_error("component t(void) {\n"
                 "  <p>one two} three</p>\n"
                 "}\n",
                 "unexpected '}' in text", 2);

    /* else without a preceding if (else at a run start) */
    expect_error("component t(void) {\n"
                 "  <p>x</p>\n"
                 "  else { <p>y</p> }\n"
                 "}\n",
                 "no preceding 'if'", 3);

    /* reserved component names */
    expect_error("component raw(void) {\n"
                 "  <p>x</p>\n"
                 "}\n",
                 "collides with the runtime", 1);
    expect_error("component tpl_x(void) {\n"
                 "  <p>x</p>\n"
                 "}\n",
                 "collides with the runtime", 1);

    /* @raw misuse */
    expect_error("component t(void) {\n"
                 "  @raw\n"
                 "}\n",
                 "@raw expects exactly one argument", 2);
    expect_error("component t(const char *s) {\n"
                 "  @raw(s) { <p>block</p> }\n"
                 "}\n",
                 "@raw expects exactly one argument", 2);

    /* empty interpolation */
    expect_error("component t(void) {\n"
                 "  <p>{ }</p>\n"
                 "}\n",
                 "empty { } interpolation", 2);

    /* interpolation outside a quoted attribute value */
    expect_error("component t(const char *s) {\n"
                 "  <p { s }=\"x\">y</p>\n"
                 "}\n",
                 "interpolation outside a quoted attribute", 2);

    /* boolean attribute without a condition block */
    expect_error("component t(bool b) {\n"
                 "  <input checked?=b/>\n"
                 "}\n",
                 "expected '{' after '?='", 2);

    /* unterminated tag */
    expect_error("component t(void) {\n"
                 "  <p never closed\n"
                 "}\n",
                 "unterminated tag", 4);

    /* unterminated comment */
    expect_error("component t(void) {\n"
                 "  <!-- no end\n"
                 "}\n",
                 "unterminated <!-- comment", 4);

    /* unterminated component body */
    expect_error("component t(void) {\n"
                 "  <p>x</p>\n",
                 "missing '}'", 3);

    /* statement keyword as a text run start without a block */
    expect_error("component t(void) {\n"
                 "  <p>a</p>\n"
                 "  for a day\n"
                 "}\n",
                 "unbalanced", 4);

    /* no components at all (positionless: line 0) */
    expect_error("// just a comment\n", "no components found", 0);

    /* top level junk */
    expect_error("<p>markup</p>\n", "expected 'component'", 1);

    /* unterminated C string inside an expression */
    expect_error("component t(void) {\n"
                 "  { \"unterminated\n"
                 "}\n",
                 "unterminated string literal", 4);
}

/* ------------------------------------------------------------------ */

int main(void)
{
    test_golden_simple();
    test_golden_control_flow();
    test_golden_attributes();
    test_features();
    test_children();
    test_children_with();
    test_fragment_once();
    test_fragment_once_errors();
    test_html_validation_valid();
    test_html_validation_errors();
    test_attr_contexts();
    test_attr_context_errors();
    test_raw_text_elements();
    test_keyword_text_escaping();
    test_no_params_and_empty_body();
    test_errors();
    return test_report();
}