/* Generated by ctmpl from /stuff/programming/c-http/examples/tpl/home.thtml - DO NOT EDIT */
#include "home_templ.h"

/* render-once handles (see @once) */
static TplOnce note_style = {.name = "note_style"};

static void tpl__block_1(TplOut *out, const HomePageData *p)
{
    tpl_lit(out, "\n    ");
#line 51 "/stuff/programming/c-http/examples/tpl/home.thtml"
    tpl_feature_note(out);
    tpl_lit(out, "\n    <h1>");
#line 52 "/stuff/programming/c-http/examples/tpl/home.thtml"
    tpl_esc(out, (p->title));
    tpl_lit(out, "</h1>");
#line 53 "/stuff/programming/c-http/examples/tpl/home.thtml"
    if (p->logged_in) {
        tpl_lit(out, "\n      <p>Welcome back, <b>");
#line 54 "/stuff/programming/c-http/examples/tpl/home.thtml"
        tpl_esc(out, (p->user));
        tpl_lit(out, "</b>!</p>");
    } else {
        tpl_lit(out, "\n      <p><a href=\"/login\">Log in</a> to see more.</p>");
    }
    tpl_lit(out, "\n    <hr ");
#line 58 "/stuff/programming/c-http/examples/tpl/home.thtml"
    if (p->logged_in) {
        tpl_lit(out, " noshade");
    }
    tpl_lit(out, "/>\n    <p>Server features:</p>\n    <!-- @fragment: /frag renders ONLY this block — htmx swaps it in -->\n    ");
#line 61 "/stuff/programming/c-http/examples/tpl/home.thtml"
    {
        tpl_frag_begin(out, ("links"));
        tpl_lit(out, "\n      ");
#line 62 "/stuff/programming/c-http/examples/tpl/home.thtml"
        tpl_link_list(out, p);
        tpl_frag_end(out);
    }
    tpl_lit(out, "\n    ");
#line 64 "/stuff/programming/c-http/examples/tpl/home.thtml"
    tpl_feature_note(out);
}
static void tpl__block_1_adapter(TplOut *out, void *tpl_data)
{
    tpl__block_1(out, tpl_data);
}

void tpl_feature_note(TplOut *out)
{
#line 8 "/stuff/programming/c-http/examples/tpl/home.thtml"
    tpl_lit(out, "\n  <!-- @once: the <style> reaches the page exactly once per render,\n       no matter how often this component is used on it -->\n  ");
#line 11 "/stuff/programming/c-http/examples/tpl/home.thtml"
    if (tpl_once_begin(out, &(note_style))) {
        tpl_lit(out, "\n    <style>.note { color: #666; font-size: 0.9em; }</style>");
    }
    tpl_lit(out, "\n  <p class=\"note\">rendered server-side with ctmpl</p>");
}

void tpl_nav_bar(TplOut *out)
{
#line 17 "/stuff/programming/c-http/examples/tpl/home.thtml"
    tpl_lit(out, "\n  <nav>\n    <a href=\"/\">Home</a> |\n    <a href=\"/api/status\">API status</a> |\n    <a href=\"/ws.html\">Chat demo</a>\n  </nav>");
}

void tpl_link_list(TplOut *out, const HomePageData *p)
{
#line 25 "/stuff/programming/c-http/examples/tpl/home.thtml"
    tpl_lit(out, "\n  <ul class=\"links\">");
#line 27 "/stuff/programming/c-http/examples/tpl/home.thtml"
    for (size_t i = 0; i < p->link_count; i++) {
        tpl_lit(out, "\n    <li><a href=\"");
#line 28 "/stuff/programming/c-http/examples/tpl/home.thtml"
        tpl_attr_url(out, (tpl_url(out, p->links[i].url)));
        tpl_lit(out, "\">");
#line 28 "/stuff/programming/c-http/examples/tpl/home.thtml"
        tpl_esc(out, (p->links[i].name));
        tpl_lit(out, "</a></li>");
    }
    tpl_lit(out, "\n  </ul>");
}

void tpl_layout(TplOut *out, TplChildren *children)
{
#line 33 "/stuff/programming/c-http/examples/tpl/home.thtml"
    tpl_lit(out, "\n  <!DOCTYPE html>\n  <html lang=\"en\">\n    <head>\n      <meta charset=\"utf-8\"/>\n      <title>c-http example</title>\n    </head>\n    <body>\n      ");
#line 41 "/stuff/programming/c-http/examples/tpl/home.thtml"
    tpl_nav_bar(out);
    tpl_lit(out, "\n      <main>\n        ");
#line 43 "/stuff/programming/c-http/examples/tpl/home.thtml"
    if (children != NULL && children->fn != NULL) {
        children->fn(out, children->data);
    }
    tpl_lit(out, "\n      </main>\n    </body>\n  </html>");
}

void tpl_home(TplOut *out, const HomePageData *p)
{
#line 49 "/stuff/programming/c-http/examples/tpl/home.thtml"
    tpl_lit(out, "\n  ");
#line 50 "/stuff/programming/c-http/examples/tpl/home.thtml"
    {
        TplChildren tpl_children = {tpl__block_1_adapter, (void *)(p)};
        tpl_layout(out, &tpl_children);
    }
}

