/* Generated by ctmpl from /stuff/programming/c-http/examples/tpl/home.thtml - DO NOT EDIT */
#ifndef HOME_TEMPL_H
#define HOME_TEMPL_H

#include "c_http_tpl.h"

#include "home_data.h"

void tpl_feature_note(TplOut *out);
void tpl_nav_bar(TplOut *out);
void tpl_link_list(TplOut *out, const HomePageData *p);
void tpl_layout(TplOut *out, TplChildren *children);
void tpl_home(TplOut *out, const HomePageData *p);

#endif /* HOME_TEMPL_H */
