#!/usr/bin/env python3
"""
Amalgamation script: generates a single-header library from the multi-file source.

Usage:
  python3 scripts/amalgamate.py [--output c_http_single.h]

The output file can be consumed in two ways:

1. Single-header mode (stb-style):
   // In exactly ONE .c file:
   #define C_HTTP_IMPLEMENTATION
   #include "c_http_single.h"

   // In all other files:
   #include "c_http_single.h"

2. Or just include it and link the compiled .c files normally.

Requires: zlib (for gzip encoding support)
"""

import os
import re
import sys
import subprocess

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.dirname(SCRIPT_DIR)

HEADER_FILES = [
    os.path.join(ROOT_DIR, "include", "c_http.h"),
    os.path.join(ROOT_DIR, "include", "c_http_assert.h"),
]

SOURCE_FILES = [
    os.path.join(ROOT_DIR, "src", "c_http.c"),
    os.path.join(ROOT_DIR, "src", "c_http_encoder.c"),
]

OUTPUT_DEFAULT = os.path.join(ROOT_DIR, "c_http_single.h")

# Our own includes to strip during amalgamation
OUR_HEADERS = {"c_http.h", "c_http_assert.h"}


def strip_include_guard(content):
    """Remove #ifndef/#define/#endif include guard lines."""
    lines = content.split("\n")
    result = []
    skip_endif = False
    for i, line in enumerate(lines):
        stripped = line.strip()
        # Skip #ifndef / #define guard at top
        if i == 0 and stripped.startswith("#ifndef"):
            skip_endif = True
            continue
        if i == 1 and stripped.startswith("#define") and skip_endif:
            continue
        # Skip final #endif
        if skip_endif and stripped == "#endif" and i >= len(lines) - 3:
            continue
        result.append(line)
    return "\n".join(result)


def strip_own_includes(content):
    """Remove #include lines that reference our own headers."""
    lines = content.split("\n")
    result = []
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("#include \""):
            header = stripped.split('"')[1]
            if header in OUR_HEADERS:
                continue
        result.append(line)
    return "\n".join(result)


def dedup_includes(content):
    """Remove duplicate #include lines (keep first occurrence)."""
    seen = set()
    lines = content.split("\n")
    result = []
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("#include <") and stripped in seen:
            continue
        if stripped.startswith("#include <"):
            seen.add(stripped)
        result.append(line)
    return "\n".join(result)


def get_version():
    """Extract C_HTTP_VERSION from c_http.h."""
    with open(HEADER_FILES[0]) as f:
        for line in f:
            m = re.search(r'#define C_HTTP_VERSION\s+"([^"]+)"', line)
            if m:
                return m.group(1)
    return "unknown"


def main():
    output = OUTPUT_DEFAULT
    if "--output" in sys.argv:
        idx = sys.argv.index("--output")
        output = sys.argv[idx + 1]

    version = get_version()

    # --- Header section (declarations) ---
    header_parts = []
    for f in HEADER_FILES:
        with open(f) as fh:
            content = fh.read()
        content = strip_include_guard(content)
        content = strip_own_includes(content)
        header_parts.append(content.strip())

    # --- Implementation section ---
    impl_parts = []
    for f in SOURCE_FILES:
        with open(f) as fh:
            content = fh.read()
        content = strip_own_includes(content)
        impl_parts.append(content.strip())

    # --- Assemble ---
    banner = f"""/* ==========================================================================
 * c_http_single.h — Single-header amalgamation of c-http v{version}
 *
 * Generated by scripts/amalgamate.py — DO NOT EDIT
 *
 * Usage (stb-style, single-header mode):
 *   // In exactly ONE .c file:
 *   #define C_HTTP_IMPLEMENTATION
 *   #include "c_http_single.h"
 *
 *   // In all other files:
 *   #include "c_http_single.h"
 *
 * Requires: zlib (link with -lz)
 * Source:   https://github.com/maxischmaxi/c-http
 * ========================================================================== */

#ifndef C_HTTP_SINGLE_H
#define C_HTTP_SINGLE_H

"""

    header_section = dedup_includes("\n\n".join(header_parts))
    impl_section = dedup_includes("\n\n".join(impl_parts))

    output_content = (
        banner
        + header_section
        + "\n\n#endif /* C_HTTP_SINGLE_H */\n\n"
        + "#ifdef C_HTTP_IMPLEMENTATION\n"
        + "#ifndef C_HTTP_IMPLEMENTATION_GUARD\n"
        + "#define C_HTTP_IMPLEMENTATION_GUARD\n\n"
        + impl_section
        + "\n\n#endif /* C_HTTP_IMPLEMENTATION_GUARD */\n"
        + "#endif /* C_HTTP_IMPLEMENTATION */\n"
    )

    with open(output, "w") as f:
        f.write(output_content)

    line_count = output_content.count("\n") + 1
    print(f"Generated {output} ({line_count} lines, v{version})")
    return 0


if __name__ == "__main__":
    sys.exit(main())